feat: Add mentor cards
richyen/ismp pull request #16
Opened 2020-05-16 19:20 UTC by misunchoi

https://xd.adobe.com/view/5d144dfd-70e7-4cac-6b17-088a5b93ebcd-2b25/screen/117d6778-6199-4d99-899c-3968bc067b4d/ISMP-Website-Mentorship-FindAMentor

2020-05-16 19:40 UTC, douglaschan32167 requested changes
Thanks Misun! It turns out that we don't want people to directly contact mentors, so I think we can remove the get in touch button. Otherwise, it looks good!

2020-05-16 19:40 UTC, douglaschan32167 commented on frontend/src/components/MentorCards/MentorCards.jsx
> +    education: 'U.C. Berkley',
nit: Berkeley

2020-05-16 19:40 UTC, douglaschan32167 commented on frontend/src/components/MentorCards/MentorCards.jsx
> +              <Button>Get in touch</Button>
Sorry, the image was a bit outdated. From our meetings it seems like we don't want people to be able to directly contact a mentor. Could you remove this or comment it out for now?

2020-05-16 22:30 UTC, misunchoi commented
> Thanks Misun! It turns out that we don't want people to directly contact mentors, so I think we can remove the get in touch button. Otherwise, it looks good!

2020-05-16 22:31 UTC, misunchoi commented
sorry didn't meant to close the PR haha but made the fix!

2020-05-17 02:01 UTC, douglaschan32167 approved these changes
LGTM

2020-05-17 02:01 UTC, merged