Add school table
richyen/ismp pull request #19
Opened 2020-05-17 22:35 UTC by douglaschan32167

Add API endpoint for schools with initial schema.  Lots of boiler-plate code

2020-05-17 22:49 UTC, richyen requested changes
Can you add some fixtures for this app/object?

2020-05-18 05:09 UTC, douglaschan32167 commented
Added 3 objects to fixtures and updated api-entrypoint.sh to load it.

2020-05-18 05:23 UTC, richyen approved these changes

2020-05-18 05:23 UTC, richyen commented on backend/api/blogpost_content/models.py
> +
Run your code through `pylint` to remove extra blank lines (and fix EOF endings)

2020-05-18 05:23 UTC, merged