Add full application form
richyen/ismp pull request #41
Opened 2020-05-29 07:47 UTC by kailanjian

me and jesse worked on this

2020-05-29 16:10 UTC, richyen requested changes
small design decision -- date v. datetime.  Don't mean to be nitpicky, but just wanted to raise awareness, in case you guys didn't realize there was `date` function also

2020-05-29 16:10 UTC, richyen commented on backend/api/application_form/migrations/0005_applicationform_birth_date.py
> +            field=models.DateTimeField(default=datetime.now(), max_length=100),
This should be a date field, not a datetime

2020-05-29 16:10 UTC, richyen commented on backend/api/application_form/models.py
> +    birth_date = models.DateTimeField(max_length=100)
date v datetime?

2020-05-29 16:10 UTC, richyen commented on backend/api/application_form/tests.py
> +            "birth_date": "2020-05-07T01:05:00Z",
date v. datetime?

2020-05-29 18:31 UTC, kailanjian commented on backend/api/application_form/migrations/0005_applicationform_birth_date.py
> +            field=models.DateTimeField(default=datetime.now(), max_length=100),
I see, I didn't know there was a date field, I just used the first thing I saw

2020-05-29 21:56 UTC, richyen commented on backend/api/application_form/migrations/0005_applicationform_birth_date.py
> +            field=models.DateTimeField(default=datetime.now(), max_length=100),
@douglaschan32167 -- What do you think? Stick with `datetime`, or change to `date`?

2020-05-30 16:57 UTC, kailanjian commented
I started changing this to date, however there is an issue which we may want to consider: it looks like JavaScript dates are serialized to the format that DateTime expects rather than Date. For that reason I don't know how to send the date without changing the frontend code substantively. So I can keep looking into this, but not sure if it's worth it

2020-05-31 05:15 UTC, douglaschan32167 commented on backend/api/application_form/models.py
> +    birth_date = models.DateTimeField(max_length=100)
If it's hard on the frontend, I'm okay with it being a datetime. Still, why do we even need this information in the first place? That's a little bit weird. It also makes the sensitivity of personal information we have much higher. I may need to push back on this.

2020-05-31 05:21 UTC, douglaschan32167 commented on backend/api/application_form/migrations/0005_applicationform_birth_date.py
> +            field=models.DateTimeField(default=datetime.now(), max_length=100),
I'm okay with sticking with datetime.

2020-05-31 05:29 UTC, douglaschan32167 commented on backend/api/application_form/models.py
> +    birth_date = models.DateTimeField(max_length=100)
Another option is we override the save function in the model like https://stackoverflow.com/questions/23887961/django-how-can-i-modify-text-before-save-them-to-database/23888157

But I could see how that would make working in the future more confusing. I say we just keep it as a datetime. I posted a question about whether we even need this info in the questions/concerns section of the basecamp.

2020-05-31 05:38 UTC, douglaschan32167 approved these changes

2020-05-31 05:38 UTC, merged